version: "2.0"
services:
  springboot:
    image: wk:1.0
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/wikicode
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo:3.4
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge